kind: Deploy
description: Ingress controller for garden development
name: nginx-ephemeral
type: helm
dependencies:
  - deploy.default-backend
spec:
  chart:
    name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version: 4.0.13
  releaseName: garden-nginx
  atomic: false
  values:
    name: ingress-controller
    controller:
      extraArgs:
        default-backend-service: ${var.namespace}/default-backend
      kind: Deployment
      replicaCount: 1
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 1
      minReadySeconds: 1
      tolerations: ${var.system-tolerations}
      nodeSelector: ${var.system-node-selector}
      admissionWebhooks:
        enabled: false
      ingressClassResource:
        name: nginx
        enabled: true
        default: true
      service:
        annotations:
          "kubernetes.namespace.so/expose": "true"
          "kubernetes.namespace.so/exposed-port-80": "wildcard"
          "kubernetes.namespace.so/exposed-port-443": "wildcard"
        type: LoadBalancer
    defaultBackend:
      enabled: false
