kind: Deploy
name: nginx-ingress-class
description: Special manifests for installing nginx ingress class
type: kubernetes
spec:
  manifests:
    - apiVersion: networking.k8s.io/v1
      kind: IngressClass
      metadata:
        name: nginx
      spec:
        controller: k8s.io/ingress-nginx
